### PR TITLE
Add UserScript metadata block

### PR DESCRIPTION
**Pull request by alpernebbi**
I found out that `facebook.js` works good as a userscript in Greasemonkey with Firefox 50, and decided to write a proper metadata block for it. This should also be compatible with Tampermonkey (for Chrome), but I haven't tested that.

### CODE REVIEW

**Comment by ageitgey** [comment]
Does this cause any side effects when it's loaded as a normal Chrome extension or Firefox add-on?

**Comment by jtojnar** [comment]
No. Comments are ignored by extensions. Though now that the extension is on the Add-On Portal, the user script is probably pointless. Also, if you want to add some functionality depending on the `browser` API, the user script would break.

**Comment by alpernebbi** [comment]
It's great that the extension has made it to addons.mozilla.org as well! But people who already use other user scripts would prefer to install this as a user script if possible. Right now, I'm using it like this, but I have to manually update the user script every time you update it. Merging this metadata block would automate that as well (every time you bump up the `@version`).

> Also, if you want to add some functionality depending on the `browser` API, the user script would break.

If that's a concern for you, feel free to close the pull request. (I guess with the localization, it will be.)

**Comment by bunnyhero** [comment]
presumably, in userscript form, this would allow usage in safari as well?

**Comment by ageitgey** [comment]
Since we are about to add translation support, this will stop working as a user script. So I don't want to merge this and then immediate break it. Sorry :(

But feel free to create a work that works as a user script if you prefer using it that way.

**Pull request closed without merging**
