### PR TITLE
tr_TR locale translation support

### PR DESCRIPTION
**Pull request by us**

### CODE REVIEW

**Comment by behram** [comment]
@ageitgey this pr have full tr_TR translation i am closing my pr from https://github.com/ageitgey/show-facebook-computer-vision-tags/pull/37. thanks @saritekin

**Comment by us** [comment]
corrected tr_TR messages directory

**Comment by ageitgey** [comment]
Thanks!

**Comment by jtojnar** [comment]
This will not work. The `if` branch for actually loading the language 
file is missing.

**Pull request merged**
